const appName = "EBRicodom";
const phone = "+213 671 18 01 69";
const email = "contact@globalads.dz";
const adress = "Les 4 chemins à coté de la gare routière, Béjaia.";

const texts = {
    "FR" : {
        "text1" : "Quel service cherchez vous ?",
        "text2" : "Vous avez besoins d'aide ?",
        "text3" : "Appeler-nous",
        "text4" : "Veuillez remplir tous les champs",
        "text5" : "Contactez-nous",
        "text6" : "Nom complet",
        "text7" : "Adresse email",
        "text8" : "Numéro de téléphone",
        "text9" : "Votre message",
        "text10" : "Rechercher",
        "text11" : "Montant de l'intervention",
        "text12" : "Entre",
        "text13" : "et",
        "text14" : "Demander une intervention",
        "text15" : "Nom",
        "text16" : "Prénom",
        "text17" : "Adresse",
        "text18" : "Numéro de téléphone",
        "text19" : "Adresse email",
        "text20" : "Type de l'intervention",
        "text21" : "En urgence",
        "text22" : "Sur rendez-vous",
        "text23" : "Selectionnez le jour de l'intervention",
        "text24" : "Selectionnez l'heure de l'intervention",
        "text25" : "Service",
        "text26" : "Paiment",
        "text27" : "Passer la commande",
        "text28" : "TTC",
        "text29" : "A propos de nous",
        "text30" : "Accueil",
        "text31" : "Contact",
        "text32" : "Recherche",
        "text33" : "Langue",
        "text34" : "Français",
        "text35" : "Arabe",
        "text36" : "Envoyer le message",
        "text37" : "Description de l'intervention",
        "text38" : "Devis sur place",
        "text39" : "Coordonnés GPS",
        "text40" : "DONNER MA LOCALISATION",
        
    },
    "AR" : {
        "text1" : "ما الخدمة التي تبحث عنها ؟",
        "text2" : "هل تحتاج مساعدة ؟",
        "text3" : "اتصل بنا",
        "text4" : "رجاءا اكمل جميع الحقول",
        "text5" : "أرسل لنا رسالة",
        "text6" : "الاسم الكامل",
        "text7" : "البريد الإلكتروني",
        "text8" : "رقم الهاتف",
        "text9" : "رسالتك",
        "text10" : "بحث",
        "text11" : "مقدار التدخل",
        "text12" : "بين",
        "text13" : "و",
        "text14" : "طلب التدخل",
        "text15" : "اللقب",
        "text16" : "الاسم",
        "text17" : "العنوان",
        "text18" : "رقم الهاتف",
        "text19" : "البريد الإلكتروني",
        "text20" : "نوع التدخل",
        "text21" : "طارئ",
        "text22" : "تحديد موعد",
        "text23" : "حدد يوم التدخل",
        "text24" : "حدد وقت التدخل",
        "text25" : "الخدمة",
        "text26" : "الدفع",
        "text27" : "تأكيد الطلب",
        "text28" : "شامل الضريبة",
        "text29" : "معلومات عنا",
        "text30" : "الرئيسية",
        "text31" : "مراسلة",
        "text32" : "بحث",
        "text33" : "اللغة",
        "text34" : "الفرنسية",
        "text35" : "العربية",
        "text36" : "أرسل الرسالة",
        "text37" : "وصف التدخل",
        "text38" : "التسعير",
        "text39" : "احداثيات الموقع",
        "text40" : "تقديم موقعي",

    }
}


export {appName, phone, email, adress, texts}
